feat: force http1 to avoid issues with long-lived http2 sessions
adobe/helix-pipeline pull request #903
Opened 2020-12-04 16:47 UTC by stefan-guggisberg

The upcoming/new I/O Runtime environment is Azure-based and supports HTTP/2. This might lead to issues with long-lived HTTP/2 sessions.

2020-12-04 16:50 UTC, trieloff approved these changes

2020-12-05 05:46 UTC, tripodsan commented on src/utils/Downloader.js
> -    if (options.forceHttp1 || process.env.HELIX_PIPELINE_FORCE_HTTP1) {
keep the `if` and just set the  `process.env.HELIX_PIPELINE_FORCE_HTTP1 = true`

2020-12-05 05:46 UTC, tripodsan requested changes
keep the `if` so we can enable it later again

2020-12-06 01:10 UTC, tripodsan approved these changes

2020-12-06 14:47 UTC, merged